### PR TITLE
ARM architecture compatibility

### LINKED ISSUE #120: Can't start Servers on arm system
**Describe the bug**
I've tried setting up the cloud but when trying to start a server it just goes in a loop. The logs show that the VM option 'UseSSE' is unreconized

**To Reproduce**
Try to create a server on an system with the arm architecture

**Expected behavior**
The server shouldn't get unrecognized VM options and be able to start

**Stacktrace**
```
 $ cat proxy/Proxy_5dcfAT.log 
Unrecognized VM option 'UseSSE=3'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Operating System (please complete the following information):**
 - OS: Oracle Linux Server
 - Version: 8.6
 - Architecture: aarch64

### PR DESCRIPTION
**Pull request by HyperTNTClown**
## Overview

**Fixes #120**

## Description
Just a simple check in the DefaultPropertiesProviderImplementations for the Server and Proxy Groups
## Checklist

- [X] I included all information required in the sections above
- [x] I tested my changes and approved their functionality 
- [x] I ensured my changes do not break other parts of the code
- [X] I read and followed the [contribution guidelines](https://github.com/TimoCloud/TimoCloud/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by HyperTNTClown** [comment]
Okay I'm feeling a bit dumb. When testing my changes in a seperate file everything works. But when testing the compiled jenkins build. It still adds the parameter. Can someone look at my code and tell me if I did something wrong?

My code for testing my changes is this:                                                                                                                                                                                      

```
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;

class Main {
  public static void main(String[] args) {
    System.out.println(getJavaParameters().contains("-XX:UseSSE=3"));
    System.out.println(getJavaParametersS().contains("-XX:UseSSE=3"));
  }
  public static List<String> getJavaParameters() {
        if (System.getProperty("os.arch").contains("arm") || System.getProperty("os.arch").contains("aarch64")) return Arrays.asList(
                "-Dfile.encoding=UTF8",
                "-XX:+UseG1GC",
                "-XX:+UnlockExperimentalVMOptions",
                "-XX:+DoEscapeAnalysis",
                "-XX:+UseCompressedOops",
                "-XX:MaxGCPauseMillis=10",
                "-XX:GCPauseIntervalMillis=100",
                "-XX:+UseAdaptiveSizePolicy",
                "-XX:ParallelGCThreads=2");
        else return Arrays.asList(
                "-Dfile.encoding=UTF8",
                "-XX:+UseG1GC",
                "-XX:+UnlockExperimentalVMOptions",
                "-XX:+DoEscapeAnalysis",
                "-XX:+UseCompressedOops",
                "-XX:MaxGCPauseMillis=10",
                "-XX:GCPauseIntervalMillis=100",
                "-XX:+UseAdaptiveSizePolicy",
                "-XX:ParallelGCThreads=2",
                "-XX:UseSSE=3");
    }

   public static List<String> getJavaParametersS() {
        if (System.getProperty("os.arch").contains("arm") || System.getProperty("os.arch").contains("aarch64")) return Arrays.asList("-Dfile.encoding=UTF8", "-XX:+UnlockExperimentalVMOptions", "-XX:+DoEscapeAnalysis", "-XX:+UseCompressedOops", "-XX:MaxGCPauseMillis=10", "-XX:GCPauseIntervalMillis=100", "-XX:+UseAdaptiveSizePolicy", "-XX:ParallelGCThreads=2");
        else return Arrays.asList("-Dfile.encoding=UTF8", "-XX:+UnlockExperimentalVMOptions", "-XX:+DoEscapeAnalysis", "-XX:+UseCompressedOops", "-XX:MaxGCPauseMillis=10", "-XX:GCPauseIntervalMillis=100", "-XX:+UseAdaptiveSizePolicy", "-XX:ParallelGCThreads=2", "-XX:UseSSE=3");
    }
}
```

And it outputs:
```
$ java main.java
false
false
```

I'm stuck

**Comment by HyperTNTClown** [comment]
Sorry for the unnecessary commits, I was working on my own additions and forgot to use a different branch.

**Comment by TheMagBum** [comment]
Could you please check if your updates work and the problem is fixed?

**Comment by HyperTNTClown** [comment]
Oh yeah sorry, it's working

**Comment by TheMagBum** [comment]
Okay, can you please increse the version in the pom.xml`s

**Comment by TheMagBum** [comment]
Thank you for you pull request :)

**Pull request merged**
