### PR TITLE
Adds support for Docker.

### PR DESCRIPTION
**Pull request by ghost**
Support for Docker in the Timocloud via Dockerfile and a docker-compose.yml .

If it is to be used, please keep the credits in the Dockerfile. Thank you 😉

### CODE REVIEW

**Comment by Dreamtrailtv** [comment]
Do the packages that are not used for the execution of Timocloud have a justified use? Otherwise this would be a bit unnecessary and could be removed.

**Comment by ghost** [comment]
> Do the packages that are not used for the execution of Timocloud have a justified use? Otherwise this would be a bit unnecessary and could be removed.

I cleaned up the Dockerfile a bit - you're right, a few packages are relatively unnecessary.

**Review by TheMagBum — CHANGES_REQUESTED** [review]
Great idea!
Can you please increase the version?

**Comment by ghost** [comment]
> Great idea! Can you please increase the version?

Yea, updated so on build it downloads the latest version. 👍

**Pull request merged**
